# Development Dockerfile
FROM node:18-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

EXPOSE 3000

ENV PORT 3000
ENV NODE_ENV development

CMD ["npm", "run", "dev"]